# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shaft_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1186, 549)
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(920, 500, 112, 34))
        self.pushButton_Exit.setAutoDefault(False)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 191))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_GetShaft = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_GetShaft.setGeometry(QtCore.QRect(40, 30, 401, 34))
        self.pushButton_GetShaft.setAutoDefault(False)
        self.pushButton_GetShaft.setObjectName("pushButton_GetShaft")
        self.textEdit_filename = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_filename.setGeometry(QtCore.QRect(10, 80, 461, 91))
        self.textEdit_filename.setReadOnly(True)
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 381, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 180, 81, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit_maxTension = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxTension.setGeometry(QtCore.QRect(120, 180, 101, 25))
        self.lineEdit_maxTension.setObjectName("lineEdit_maxTension")
        self.pushButton_PlotAxTor = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_PlotAxTor.setGeometry(QtCore.QRect(10, 290, 211, 28))
        self.pushButton_PlotAxTor.setAutoDefault(False)
        self.pushButton_PlotAxTor.setObjectName("pushButton_PlotAxTor")
        self.lineEdit_maxTorque = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxTorque.setGeometry(QtCore.QRect(120, 210, 101, 25))
        self.lineEdit_maxTorque.setObjectName("lineEdit_maxTorque")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 71, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_maxMoment = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxMoment.setGeometry(QtCore.QRect(120, 240, 101, 25))
        self.lineEdit_maxMoment.setObjectName("lineEdit_maxMoment")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 81, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_maxMoment_loc = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxMoment_loc.setGeometry(QtCore.QRect(240, 240, 101, 25))
        self.lineEdit_maxMoment_loc.setObjectName("lineEdit_maxMoment_loc")
        self.lineEdit_maxTorque_loc = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxTorque_loc.setGeometry(QtCore.QRect(240, 210, 101, 25))
        self.lineEdit_maxTorque_loc.setObjectName("lineEdit_maxTorque_loc")
        self.lineEdit_maxTension_loc = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_maxTension_loc.setGeometry(QtCore.QRect(240, 180, 101, 25))
        self.lineEdit_maxTension_loc.setObjectName("lineEdit_maxTension_loc")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(100, 150, 91, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(220, 150, 91, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_TRy = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_TRy.setGeometry(QtCore.QRect(70, 40, 101, 25))
        self.lineEdit_TRy.setText("")
        self.lineEdit_TRy.setObjectName("lineEdit_TRy")
        self.lineEdit_RRy = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_RRy.setGeometry(QtCore.QRect(260, 40, 101, 25))
        self.lineEdit_RRy.setText("")
        self.lineEdit_RRy.setObjectName("lineEdit_RRy")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(210, 40, 31, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(210, 70, 31, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_RRz = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_RRz.setGeometry(QtCore.QRect(260, 70, 101, 25))
        self.lineEdit_RRz.setText("")
        self.lineEdit_RRz.setObjectName("lineEdit_RRz")
        self.lineEdit_TRz = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_TRz.setGeometry(QtCore.QRect(70, 70, 101, 25))
        self.lineEdit_TRz.setText("")
        self.lineEdit_TRz.setObjectName("lineEdit_TRz")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 41, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_Moments = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Moments.setGeometry(QtCore.QRect(230, 290, 141, 28))
        self.pushButton_Moments.setAutoDefault(False)
        self.pushButton_Moments.setObjectName("pushButton_Moments")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 151, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(220, 20, 141, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 41, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit_Thrust = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Thrust.setGeometry(QtCore.QRect(70, 100, 101, 25))
        self.lineEdit_Thrust.setText("")
        self.lineEdit_Thrust.setObjectName("lineEdit_Thrust")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 210, 381, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 111, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_maxSigm = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSigm.setGeometry(QtCore.QRect(160, 70, 101, 25))
        self.lineEdit_maxSigm.setObjectName("lineEdit_maxSigm")
        self.pushButton_PlotStresses = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_PlotStresses.setGeometry(QtCore.QRect(20, 290, 161, 28))
        self.pushButton_PlotStresses.setAutoDefault(False)
        self.pushButton_PlotStresses.setObjectName("pushButton_PlotStresses")
        self.lineEdit_maxSiga = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSiga.setGeometry(QtCore.QRect(160, 100, 101, 25))
        self.lineEdit_maxSiga.setObjectName("lineEdit_maxSiga")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 131, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_maxStatic = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxStatic.setGeometry(QtCore.QRect(160, 130, 101, 25))
        self.lineEdit_maxStatic.setObjectName("lineEdit_maxStatic")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.lineEdit_maxStatic_loc = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxStatic_loc.setGeometry(QtCore.QRect(280, 130, 81, 25))
        self.lineEdit_maxStatic_loc.setObjectName("lineEdit_maxStatic_loc")
        self.lineEdit_maxSiga_loc = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSiga_loc.setGeometry(QtCore.QRect(280, 100, 81, 25))
        self.lineEdit_maxSiga_loc.setObjectName("lineEdit_maxSiga_loc")
        self.lineEdit_maxSigm_loc = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSigm_loc.setGeometry(QtCore.QRect(280, 70, 81, 25))
        self.lineEdit_maxSigm_loc.setObjectName("lineEdit_maxSigm_loc")
        self.pushButton_SlopeDelta = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_SlopeDelta.setGeometry(QtCore.QRect(210, 290, 161, 28))
        self.pushButton_SlopeDelta.setAutoDefault(False)
        self.pushButton_SlopeDelta.setObjectName("pushButton_SlopeDelta")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(140, 40, 91, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(260, 40, 91, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.lineEdit_maxSlope = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSlope.setGeometry(QtCore.QRect(160, 180, 101, 25))
        self.lineEdit_maxSlope.setObjectName("lineEdit_maxSlope")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(10, 180, 131, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lineEdit_maxSlope_loc = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxSlope_loc.setGeometry(QtCore.QRect(280, 180, 81, 25))
        self.lineEdit_maxSlope_loc.setObjectName("lineEdit_maxSlope_loc")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 210, 131, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.lineEdit_maxDelta_loc = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxDelta_loc.setGeometry(QtCore.QRect(280, 210, 81, 25))
        self.lineEdit_maxDelta_loc.setObjectName("lineEdit_maxDelta_loc")
        self.lineEdit_maxDelta = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_maxDelta.setGeometry(QtCore.QRect(160, 210, 101, 25))
        self.lineEdit_maxDelta.setObjectName("lineEdit_maxDelta")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 10, 661, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_d1_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d1_loc.setGeometry(QtCore.QRect(60, 50, 51, 25))
        self.lineEdit_d1_loc.setReadOnly(True)
        self.lineEdit_d1_loc.setObjectName("lineEdit_d1_loc")
        self.lineEdit_d1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d1.setGeometry(QtCore.QRect(140, 50, 51, 25))
        self.lineEdit_d1.setText("")
        self.lineEdit_d1.setObjectName("lineEdit_d1")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(50, 30, 61, 20))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(140, 30, 51, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(20, 50, 20, 20))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(20, 80, 20, 20))
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.lineEdit_d2_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d2_loc.setGeometry(QtCore.QRect(60, 80, 51, 25))
        self.lineEdit_d2_loc.setText("")
        self.lineEdit_d2_loc.setReadOnly(True)
        self.lineEdit_d2_loc.setObjectName("lineEdit_d2_loc")
        self.lineEdit_d2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d2.setGeometry(QtCore.QRect(140, 80, 51, 25))
        self.lineEdit_d2.setText("")
        self.lineEdit_d2.setObjectName("lineEdit_d2")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(20, 110, 20, 20))
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.lineEdit_d3_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d3_loc.setGeometry(QtCore.QRect(60, 110, 51, 25))
        self.lineEdit_d3_loc.setText("")
        self.lineEdit_d3_loc.setReadOnly(True)
        self.lineEdit_d3_loc.setObjectName("lineEdit_d3_loc")
        self.lineEdit_d3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d3.setGeometry(QtCore.QRect(140, 110, 51, 25))
        self.lineEdit_d3.setText("")
        self.lineEdit_d3.setObjectName("lineEdit_d3")
        self.lineEdit_d5_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d5_loc.setGeometry(QtCore.QRect(290, 80, 51, 25))
        self.lineEdit_d5_loc.setText("")
        self.lineEdit_d5_loc.setReadOnly(True)
        self.lineEdit_d5_loc.setObjectName("lineEdit_d5_loc")
        self.lineEdit_d6_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d6_loc.setGeometry(QtCore.QRect(290, 110, 51, 25))
        self.lineEdit_d6_loc.setText("")
        self.lineEdit_d6_loc.setReadOnly(True)
        self.lineEdit_d6_loc.setObjectName("lineEdit_d6_loc")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.lineEdit_d5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d5.setGeometry(QtCore.QRect(370, 80, 51, 25))
        self.lineEdit_d5.setText("")
        self.lineEdit_d5.setObjectName("lineEdit_d5")
        self.lineEdit_d4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d4.setGeometry(QtCore.QRect(370, 50, 51, 25))
        self.lineEdit_d4.setText("")
        self.lineEdit_d4.setObjectName("lineEdit_d4")
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setGeometry(QtCore.QRect(250, 110, 20, 20))
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setGeometry(QtCore.QRect(250, 50, 20, 20))
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setGeometry(QtCore.QRect(250, 80, 20, 20))
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.lineEdit_d4_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d4_loc.setGeometry(QtCore.QRect(290, 50, 51, 25))
        self.lineEdit_d4_loc.setText("")
        self.lineEdit_d4_loc.setReadOnly(True)
        self.lineEdit_d4_loc.setObjectName("lineEdit_d4_loc")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setGeometry(QtCore.QRect(370, 30, 51, 20))
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.lineEdit_d6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d6.setGeometry(QtCore.QRect(370, 110, 51, 25))
        self.lineEdit_d6.setText("")
        self.lineEdit_d6.setObjectName("lineEdit_d6")
        self.lineEdit_d7_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d7_loc.setGeometry(QtCore.QRect(510, 50, 51, 25))
        self.lineEdit_d7_loc.setText("")
        self.lineEdit_d7_loc.setReadOnly(True)
        self.lineEdit_d7_loc.setObjectName("lineEdit_d7_loc")
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setGeometry(QtCore.QRect(500, 30, 61, 20))
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.lineEdit_d8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d8.setGeometry(QtCore.QRect(590, 80, 51, 25))
        self.lineEdit_d8.setText("")
        self.lineEdit_d8.setObjectName("lineEdit_d8")
        self.lineEdit_d9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d9.setGeometry(QtCore.QRect(590, 110, 51, 25))
        self.lineEdit_d9.setText("")
        self.lineEdit_d9.setObjectName("lineEdit_d9")
        self.lineEdit_d9_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d9_loc.setGeometry(QtCore.QRect(510, 110, 51, 25))
        self.lineEdit_d9_loc.setText("")
        self.lineEdit_d9_loc.setReadOnly(True)
        self.lineEdit_d9_loc.setObjectName("lineEdit_d9_loc")
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setGeometry(QtCore.QRect(470, 50, 20, 20))
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.lineEdit_d7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d7.setGeometry(QtCore.QRect(590, 50, 51, 25))
        self.lineEdit_d7.setText("")
        self.lineEdit_d7.setObjectName("lineEdit_d7")
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        self.label_53.setGeometry(QtCore.QRect(590, 30, 51, 20))
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.lineEdit_d8_loc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_d8_loc.setGeometry(QtCore.QRect(510, 80, 51, 25))
        self.lineEdit_d8_loc.setText("")
        self.lineEdit_d8_loc.setReadOnly(True)
        self.lineEdit_d8_loc.setObjectName("lineEdit_d8_loc")
        self.label_54 = QtWidgets.QLabel(self.groupBox_5)
        self.label_54.setGeometry(QtCore.QRect(470, 80, 20, 20))
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_5)
        self.label_55.setGeometry(QtCore.QRect(470, 110, 20, 20))
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.pushButton_PlotAxTor_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_PlotAxTor_3.setGeometry(QtCore.QRect(50, 150, 161, 28))
        self.pushButton_PlotAxTor_3.setAutoDefault(False)
        self.pushButton_PlotAxTor_3.setObjectName("pushButton_PlotAxTor_3")
        self.pushButton_PlotDiameters = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_PlotDiameters.setGeometry(QtCore.QRect(410, 150, 161, 28))
        self.pushButton_PlotDiameters.setAutoDefault(False)
        self.pushButton_PlotDiameters.setObjectName("pushButton_PlotDiameters")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(790, 210, 381, 271))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_minFSfatigue = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minFSfatigue.setGeometry(QtCore.QRect(120, 50, 81, 25))
        self.lineEdit_minFSfatigue.setObjectName("lineEdit_minFSfatigue")
        self.pushButton_PlotFS = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_PlotFS.setGeometry(QtCore.QRect(190, 120, 161, 28))
        self.pushButton_PlotFS.setAutoDefault(False)
        self.pushButton_PlotFS.setObjectName("pushButton_PlotFS")
        self.lineEdit_minFSstatic = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minFSstatic.setGeometry(QtCore.QRect(120, 80, 81, 25))
        self.lineEdit_minFSstatic.setObjectName("lineEdit_minFSstatic")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_minFSstatic_loc = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minFSstatic_loc.setGeometry(QtCore.QRect(210, 80, 81, 25))
        self.lineEdit_minFSstatic_loc.setObjectName("lineEdit_minFSstatic_loc")
        self.lineEdit_minFSfatigue_loc = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minFSfatigue_loc.setGeometry(QtCore.QRect(210, 50, 81, 25))
        self.lineEdit_minFSfatigue_loc.setObjectName("lineEdit_minFSfatigue_loc")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(70, 20, 91, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(170, 20, 91, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.lineEdit_maxTorque_loc_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_maxTorque_loc_4.setGeometry(QtCore.QRect(280, 190, 81, 25))
        self.lineEdit_maxTorque_loc_4.setObjectName("lineEdit_maxTorque_loc_4")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(10, 190, 151, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_minSlopeRatio = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minSlopeRatio.setGeometry(QtCore.QRect(180, 190, 81, 25))
        self.lineEdit_minSlopeRatio.setObjectName("lineEdit_minSlopeRatio")
        self.lineEdit_minDeltaRatio = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_minDeltaRatio.setGeometry(QtCore.QRect(180, 220, 81, 25))
        self.lineEdit_minDeltaRatio.setObjectName("lineEdit_minDeltaRatio")
        self.lineEdit_maxTorque_loc_5 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_maxTorque_loc_5.setGeometry(QtCore.QRect(280, 220, 81, 25))
        self.lineEdit_maxTorque_loc_5.setObjectName("lineEdit_maxTorque_loc_5")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(10, 220, 151, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.lineEdit_FS_Static_Reqd = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_FS_Static_Reqd.setGeometry(QtCore.QRect(310, 80, 61, 25))
        self.lineEdit_FS_Static_Reqd.setText("")
        self.lineEdit_FS_Static_Reqd.setObjectName("lineEdit_FS_Static_Reqd")
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(310, 20, 51, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.lineEdit_FS_Fatigue_Reqd = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_FS_Fatigue_Reqd.setGeometry(QtCore.QRect(310, 50, 61, 25))
        self.lineEdit_FS_Fatigue_Reqd.setText("")
        self.lineEdit_FS_Fatigue_Reqd.setObjectName("lineEdit_FS_Fatigue_Reqd")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Shaft Analysis and Design"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.groupBox.setTitle(_translate("Dialog", "Input"))
        self.pushButton_GetShaft.setText(_translate("Dialog", "Open a Shaft File and Perform the Analysis "))
        self.groupBox_3.setTitle(_translate("Dialog", "Shaft Loads"))
        self.label.setText(_translate("Dialog", "Max Tension"))
        self.pushButton_PlotAxTor.setText(_translate("Dialog", "Axial-force and Torque Diagrams"))
        self.label_2.setText(_translate("Dialog", "Max Torque"))
        self.label_3.setText(_translate("Dialog", "Max Moment"))
        self.label_4.setText(_translate("Dialog", "Value"))
        self.label_5.setText(_translate("Dialog", "Location"))
        self.label_6.setText(_translate("Dialog", "Ry"))
        self.label_7.setText(_translate("Dialog", "Ry"))
        self.label_8.setText(_translate("Dialog", "Rz"))
        self.label_9.setText(_translate("Dialog", "Rz"))
        self.pushButton_Moments.setText(_translate("Dialog", "Moment Diagrams"))
        self.label_10.setText(_translate("Dialog", "Thrust Bearing Reactions"))
        self.label_11.setText(_translate("Dialog", "Radial Bearing Reactions"))
        self.label_12.setText(_translate("Dialog", "Thrust"))
        self.groupBox_4.setTitle(_translate("Dialog", "Shaft Stresses and Deflections (Ignoring Kt)"))
        self.label_13.setText(_translate("Dialog", "Max Mean Stress"))
        self.pushButton_PlotStresses.setText(_translate("Dialog", "Plot Stresses"))
        self.label_14.setText(_translate("Dialog", "Max Amplitude Stress"))
        self.label_15.setText(_translate("Dialog", "Max Static Stress"))
        self.pushButton_SlopeDelta.setText(_translate("Dialog", "Plot Slope and Deflection"))
        self.label_16.setText(_translate("Dialog", "Value"))
        self.label_17.setText(_translate("Dialog", "Location"))
        self.label_23.setText(_translate("Dialog", "Max Slope"))
        self.label_24.setText(_translate("Dialog", "Max Deflection"))
        self.groupBox_5.setTitle(_translate("Dialog", "Shaft Diameters"))
        self.lineEdit_d1_loc.setText(_translate("Dialog", "0"))
        self.label_30.setText(_translate("Dialog", "x-location"))
        self.label_31.setText(_translate("Dialog", "Diameter"))
        self.label_32.setText(_translate("Dialog", "1"))
        self.label_33.setText(_translate("Dialog", "2"))
        self.label_34.setText(_translate("Dialog", "3"))
        self.label_46.setText(_translate("Dialog", "x-location"))
        self.label_47.setText(_translate("Dialog", "6"))
        self.label_48.setText(_translate("Dialog", "4"))
        self.label_49.setText(_translate("Dialog", "5"))
        self.label_50.setText(_translate("Dialog", "Diameter"))
        self.label_51.setText(_translate("Dialog", "x-location"))
        self.label_52.setText(_translate("Dialog", "7"))
        self.label_53.setText(_translate("Dialog", "Diameter"))
        self.label_54.setText(_translate("Dialog", "8"))
        self.label_55.setText(_translate("Dialog", "9"))
        self.pushButton_PlotAxTor_3.setText(_translate("Dialog", "Re-calculate All"))
        self.pushButton_PlotDiameters.setText(_translate("Dialog", "Plot Diameters"))
        self.groupBox_6.setTitle(_translate("Dialog", "Shaft Factors of Safety"))
        self.label_18.setText(_translate("Dialog", "Mini. Fatigue F.S."))
        self.pushButton_PlotFS.setText(_translate("Dialog", "Plot Factors of Safety"))
        self.label_19.setText(_translate("Dialog", "Min. Stactic F.S."))
        self.label_21.setText(_translate("Dialog", "Value"))
        self.label_22.setText(_translate("Dialog", "Location"))
        self.label_20.setText(_translate("Dialog", "Minimum Slope Ratio"))
        self.label_25.setText(_translate("Dialog", "Minimum Deflection Ratio"))
        self.label_26.setText(_translate("Dialog", "Required"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

